2021-02-10T07:35:21.9785390+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T07:35:22.0543308+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T07:35:22.0621615+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T07:44:45.2064673+05:30 80000004-0000-f800-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T07:44:45.1424511+05:30 8000001e-0001-fa00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T07:50:22.8907590+05:30 80000014-0002-fc00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T07:50:27.2406453+05:30 8000001e-0001-fa00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T07:50:27.2412249+05:30 80000004-0000-f800-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T07:50:27.2419523+05:30 80000014-0002-fc00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T07:50:55.3365450+05:30 80000008-0000-f800-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T08:00:24.2904633+05:30 80000008-0000-f800-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T08:00:44.7279615+05:30 8000000c-0000-f800-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T08:00:46.4091354+05:30 8000000c-0000-f800-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T08:09:12.8713674+05:30 80000012-0000-f800-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T08:15:40.0610447+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T08:15:40.0771869+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T08:15:40.1114979+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T08:18:27.3093722+05:30 8000000a-0000-fa00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T08:19:42.1408790+05:30 8000000a-0000-fa00-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T10:24:07.3142258+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T10:24:07.4082660+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T10:24:07.4159637+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T10:26:41.3383282+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T10:26:41.3550398+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T10:26:41.3666166+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T10:53:56.6799241+05:30 80000004-0001-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T10:54:34.7461967+05:30 80000008-0003-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T10:57:08.2280847+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T10:57:08.2943703+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T10:57:08.3017689+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T10:58:07.4217407+05:30 80000011-0000-fc00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T10:58:28.9828924+05:30 80000011-0000-fc00-b63f-84710c7967bb [WRN] Exception encountered while log in It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.2.4.27433 (4c525020)
2021-02-10T11:00:08.9823296+05:30 8000000c-0003-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T11:02:16.4043119+05:30 8000000c-0003-fd00-b63f-84710c7967bb [WRN] Exception encountered while log in It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 122s ago, v: 2.2.4.27433 (00888f29)
2021-02-10T11:02:25.2987090+05:30 80000006-0001-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T11:02:30.6274363+05:30 80000006-0001-fd00-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T11:03:35.3475681+05:30 80000008-0001-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T11:03:47.8315977+05:30 80000008-0001-fd00-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T12:22:34.2237856+05:30 8000001b-0001-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T12:22:36.7365575+05:30 8000001b-0001-fd00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T12:26:08.7580649+05:30 80000019-0000-fc00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T12:26:09.2139495+05:30 80000019-0000-fc00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T12:38:05.7275637+05:30 8000001b-0000-fc00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T12:38:10.4674584+05:30 8000001b-0000-fc00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T12:38:52.9265215+05:30 8000001d-0001-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T12:44:08.6650881+05:30 80000020-0002-f700-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T12:44:08.6906276+05:30 8000001d-0001-fd00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T12:44:09.9387681+05:30 80000020-0002-f700-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T12:44:34.5211876+05:30 8000001f-0000-fc00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T12:53:49.0514300+05:30 8000001f-0000-fc00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T12:54:07.6975416+05:30 80000021-0000-fc00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T12:54:08.1450428+05:30 80000021-0000-fc00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T13:01:36.4344826+05:30 8000001f-0001-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T13:01:36.6898735+05:30 80000021-0001-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T13:01:38.9717175+05:30 80000021-0001-fd00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T13:01:39.2930909+05:30 8000001f-0001-fd00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T13:01:58.3319442+05:30 80000023-0001-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T13:04:05.0075568+05:30 80000023-0001-fd00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T13:05:06.1754305+05:30 80000029-0000-fc00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T13:05:06.7353718+05:30 80000029-0000-fc00-b63f-84710c7967bb [WRN] Exception encountered while log in Value cannot be null. (Parameter 'Value cannot be null. (Parameter 'String reference not set to an instance of a String. (Parameter 's')')') (aeb052d3)
2021-02-10T13:05:22.4295484+05:30 80000018-0003-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T13:05:46.0928947+05:30 80000018-0003-fd00-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T14:13:06.9534877+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T14:13:06.9721626+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T14:13:06.9776542+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T14:18:11.4623662+05:30 80000002-0002-f600-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T14:18:30.2584683+05:30 80000002-0002-f600-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T14:21:18.9694584+05:30 8000001c-0003-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T14:21:19.6723535+05:30 8000001c-0003-fd00-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T14:47:10.6149619+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T14:47:10.6323023+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T14:47:10.7613230+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T14:56:29.9303253+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T14:56:30.1945076+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T14:56:30.3312798+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T14:59:30.5685771+05:30 8000001b-0001-ff00-b63f-84710c7967bb [INF] The API for Adding new User has accessed (7a5c3d8f)
2021-02-10T14:59:41.4523090+05:30 8000001b-0001-ff00-b63f-84710c7967bb [INF] new User added successfully (dacf9157)
2021-02-10T15:04:57.2461981+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T15:04:57.2826137+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T15:04:57.2880119+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T15:07:10.2382247+05:30 80000016-0000-fb00-b63f-84710c7967bb [INF] The API for Adding new User has accessed (7a5c3d8f)
2021-02-10T15:07:37.1051672+05:30 80000016-0000-fb00-b63f-84710c7967bb [INF] new User added successfully (dacf9157)
2021-02-10T15:41:59.5363633+05:30 8000001d-0001-ff00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:41:59.5363633+05:30 8000000a-0001-fe00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:41:59.5363630+05:30 80000006-0001-fe00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:41:59.5363630+05:30 80000018-0000-fb00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:42:26.7873647+05:30 8000001d-0002-f600-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:42:35.2836771+05:30 8000001f-0001-ff00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:48:08.4217541+05:30 8000002f-0003-fd00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:51:00.5099660+05:30 8000000c-0001-fe00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:53:10.0442796+05:30 80000004-0000-f800-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:53:11.8567413+05:30 8000001a-0000-fb00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:53:25.1459320+05:30 80000004-0000-f900-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:59:33.7291707+05:30 8000000e-0002-f500-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T15:59:59.6745696+05:30 80000008-0000-f800-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:03:14.7746567+05:30 8000000a-0000-f800-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:03:14.7751670+05:30 8000000e-0001-fe00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:12:09.0711548+05:30 8000000e-0000-f800-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:12:09.0703590+05:30 80000035-0003-fd00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:12:32.8984081+05:30 8000000a-0000-f800-b63f-84710c7967bb [ERR] An error occurred using the connection to database '"fundoonotesapp"' on server '"localhost"'. (5fc3407c)
2021-02-10T16:12:32.8984081+05:30 8000000e-0001-fe00-b63f-84710c7967bb [ERR] An error occurred using the connection to database '"fundoonotesapp"' on server '"localhost"'. (5fc3407c)
2021-02-10T16:12:45.7289772+05:30 8000000a-0000-f800-b63f-84710c7967bb [ERR] An exception occurred while iterating over the results of a query for context type '"FundooRepository.Context.UserContext"'."
""System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 880
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 338
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()" (f5c7ac34)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 880
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 338
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at FundooRepository.UserRegistration.ForgotPassword(String email) in C:\Users\HP\source\repos\FundooNotes\FundooRepository\UserRegistration.cs:line 176
2021-02-10T16:12:46.5854759+05:30 8000000e-0001-fe00-b63f-84710c7967bb [ERR] An exception occurred while iterating over the results of a query for context type '"FundooRepository.Context.UserContext"'."
""System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 880
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 338
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()" (f5c7ac34)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 880
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 338
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at FundooRepository.UserRegistration.ForgotPassword(String email) in C:\Users\HP\source\repos\FundooNotes\FundooRepository\UserRegistration.cs:line 176
2021-02-10T16:12:46.9869901+05:30 8000000e-0001-fe00-b63f-84710c7967bb [WRN] Exception encountered while sending link to given mail addressAn exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call. (0f1ffdbe)
2021-02-10T16:12:47.0296112+05:30 8000000a-0000-f800-b63f-84710c7967bb [WRN] Exception encountered while sending link to given mail addressAn exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call. (0f1ffdbe)
2021-02-10T16:22:25.4478082+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T16:22:25.4845910+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T16:22:25.4909835+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T16:26:41.5869393+05:30 80000006-0000-f900-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:27:12.4237591+05:30 80000018-0002-f500-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:27:12.4245569+05:30 80000008-0000-f900-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:32:55.8820235+05:30 8000003b-0003-fd00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:33:06.6286783+05:30 8000001a-0002-f500-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:33:14.1021540+05:30 8000003d-0003-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x800704CD): An operation was attempted on a nonexistent network connection. (0x800704CD)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.TryCreateAsync(ActionContext actionContext, IList`1 factories)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-02-10T16:37:32.3922523+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T16:37:32.4335413+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T16:37:32.4378256+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T16:42:55.1744042+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T16:42:55.2023250+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T16:42:55.2444329+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T16:44:31.1110296+05:30 8000000c-0000-f900-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:45:10.5923094+05:30 8000000c-0000-f900-b63f-84710c7967bb [INF] Link has sent to given gmail to reset password (f569c740)
2021-02-10T16:53:31.0879250+05:30 8000001a-0001-fe00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:53:31.0879159+05:30 80000041-0003-fd00-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:54:29.7326313+05:30 80000021-0002-f500-b63f-84710c7967bb [INF] The API for Forgot Password has accessed (765c542c)
2021-02-10T16:55:22.4693212+05:30 80000021-0002-f500-b63f-84710c7967bb [INF] Link has sent to given gmail to reset password (f569c740)
2021-02-10T17:32:51.5161415+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2021-02-10T17:32:51.6543340+05:30  [INF] Hosting environment: "Development" (c3307c92)
2021-02-10T17:32:51.6623358+05:30  [INF] Content root path: "C:\Users\HP\source\repos\FundooNotes\FundooNotes" (b5d60022)
2021-02-10T17:41:09.5546426+05:30 80000045-0003-fd00-b63f-84710c7967bb [INF] The API for Reset Password has accessed (795d9b65)
2021-02-10T17:41:09.5559476+05:30 80000018-0000-f800-b63f-84710c7967bb [INF] The API for Reset Password has accessed (795d9b65)
2021-02-10T17:41:37.8768771+05:30 80000045-0003-fd00-b63f-84710c7967bb [INF] Password has reset successfully (934365ae)
2021-02-10T17:42:37.5106644+05:30 80000047-0003-fd00-b63f-84710c7967bb [INF] The API for Reset Password has accessed (795d9b65)
2021-02-10T17:43:19.7042834+05:30 80000047-0003-fd00-b63f-84710c7967bb [INF] Password has reset successfully (934365ae)
2021-02-10T20:59:52.2553389+05:30 80000051-0003-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T20:59:52.2553693+05:30 80000020-0000-f800-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T21:00:16.0586765+05:30 80000007-0003-fc00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T21:00:25.5141060+05:30 8000004b-0003-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x800704CD): An operation was attempted on a nonexistent network connection. (0x800704CD)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-02-10T21:00:25.5143923+05:30 80000024-0001-fe00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x800704CD): An operation was attempted on a nonexistent network connection. (0x800704CD)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-02-10T21:00:25.7413265+05:30 8000002c-0002-f700-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x800704CD): An operation was attempted on a nonexistent network connection. (0x800704CD)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-02-10T21:00:26.7130473+05:30 80000051-0003-fd00-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T21:00:26.7140996+05:30 80000007-0003-fc00-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T21:00:27.1102173+05:30 80000020-0000-f800-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T21:00:51.9915196+05:30 80000053-0003-fd00-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T21:00:52.1252563+05:30 80000053-0003-fd00-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T21:01:04.1738554+05:30 80000024-0000-f800-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T21:01:05.6644611+05:30 80000004-0002-f400-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T22:04:54.7195653+05:30 8000000e-0002-f400-b63f-84710c7967bb [INF] The API for User Login has accessed (6e903f84)
2021-02-10T22:05:00.2908312+05:30 8000000e-0002-f400-b63f-84710c7967bb [INF] User Logged Login Successfull! (eb681eda)
2021-02-10T22:46:30.8737654+05:30 80000039-0000-f800-b63f-84710c7967bb [INF] The API for Adding new User has accessed (7a5c3d8f)
2021-02-10T22:46:50.8013836+05:30 80000039-0000-f800-b63f-84710c7967bb [INF] new User added successfully (dacf9157)
